# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-01-10 00:50
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banner1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='标题1')),
                ('twotitle', models.CharField(max_length=100, verbose_name='标题2')),
                ('threetitle', models.CharField(max_length=100, verbose_name='标题3')),
                ('cover', models.ImageField(upload_to='static/img/', verbose_name='轮播图')),
                ('link_url', models.URLField(max_length=1000, verbose_name='图片链接')),
                ('idx', models.IntegerField(verbose_name='索引')),
            ],
            options={
                'verbose_name': '轮播图1',
                'verbose_name_plural': '轮播图1',
            },
        ),
        migrations.CreateModel(
            name='Banner2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('twotitle', models.CharField(max_length=50, verbose_name='标题2')),
                ('cover', models.ImageField(upload_to='static/img/', verbose_name='轮播图')),
                ('link_url', models.URLField(max_length=100, verbose_name='图片链接')),
                ('idx', models.IntegerField(verbose_name='索引')),
            ],
            options={
                'verbose_name': '轮播图2',
                'verbose_name_plural': '轮播图2',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('c_title', models.CharField(max_length=100, verbose_name='博客标题')),
                ('c_content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('c_views', models.IntegerField(default=0, verbose_name='浏览量')),
                ('c_date', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('c_author', models.CharField(max_length=30, verbose_name='作者')),
                ('c_likes', models.IntegerField(default=100, verbose_name='点赞量')),
                ('c_iamge', models.ImageField(upload_to='static/img')),
                ('is_recommend', models.BooleanField(default=False, verbose_name='是否推荐')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('c_name', models.CharField(max_length=200, verbose_name='博客分类')),
            ],
            options={
                'verbose_name': '文章创作',
                'verbose_name_plural': '文章创作',
            },
        ),
        migrations.CreateModel(
            name='Cobanner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='标题')),
                ('time', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('cover', models.ImageField(upload_to='static/img/', verbose_name='轮播图')),
                ('link_url', models.URLField(max_length=100, verbose_name='图片链接')),
                ('idx', models.IntegerField(verbose_name='索引')),
            ],
            options={
                'verbose_name': '技术交流轮播',
                'verbose_name_plural': '技术交流轮播',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='非用户匿名')),
                ('iamge', models.ImageField(upload_to='static/img')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
            ],
            options={
                'verbose_name': '评论',
                'verbose_name_plural': '评论',
            },
        ),
        migrations.CreateModel(
            name='Comment2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='非用户匿名')),
                ('iamge', models.ImageField(upload_to='static/img')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YOU1.Comment', verbose_name='提问')),
            ],
            options={
                'verbose_name': '评论2',
                'verbose_name_plural': '评论2',
            },
        ),
        migrations.CreateModel(
            name='Comment_del',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, verbose_name='非用户匿名')),
                ('iamge', models.ImageField(upload_to='static/img')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='发布时间')),
                ('content', ckeditor_uploader.fields.RichTextUploadingField()),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='YOU1.Blog', verbose_name='文章详情评论')),
            ],
            options={
                'verbose_name': '文章详情评论',
                'verbose_name_plural': '文章详情评论',
            },
        ),
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='歌名')),
                ('twotitle', models.CharField(max_length=100, verbose_name='歌手')),
                ('link_url', models.URLField(max_length=1000, verbose_name='mp3链接')),
                ('link_url2', models.URLField(max_length=1000, verbose_name='ogg链接')),
            ],
            options={
                'verbose_name': '音乐上传',
                'verbose_name_plural': '音乐上传',
            },
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_tags', models.CharField(max_length=100, verbose_name='标签')),
            ],
            options={
                'verbose_name': '标签',
                'verbose_name_plural': '标签',
            },
        ),
        migrations.AddField(
            model_name='blog',
            name='c_tags',
            field=models.ManyToManyField(to='YOU1.Tags', verbose_name='标签'),
        ),
    ]
